on:
  repository_dispatch:
    types:
      - test

jobs:
  build:
    name: build debian package from released binaries
    runs-on: ubuntu-latest
    steps:
    - run: "echo ${{ github.event_name }} event triggered this step."
    - uses: actions/checkout@v1
    - name: echo
      run: echo Run
