on:
  push:
    branches:
      - master
    paths:
      - "manifests/**"
      - ".github/workflows/kubeval.yml"
  pull_request:
name: Validate Kubernetes Manifests
jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run kubeval
        uses: instrumenta/kubeval-action@master
        # with:
        #   files: manifests
        #   version: "1.14"
