# name: CI
# on:
#   - push
# jobs:
#   test:
#     name: 'Test'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#         with:
#           fetch-depth: 1
#       - run: npm install
#       - run: npm run build
#       - name: 'Get changed files'
#         uses: futuratrepadeira/changed-files@master
#         with:
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
#         id: changed_files
#       - name: 'Echo'
#         run: |
#           echo ${{ steps.changed_files.outputs.files_created }}
#           echo ${{ steps.changed_files.outputs.files_updated }}

name: test
on: [push]

jobs:
  opa_test:
    runs-on: ubuntu-latest
    name: Run opa
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Get changed files
      uses: lots0logs/gh-action-get-changed-files@2.0.5
      id: changed
    - name: Run with opa test
      uses: b4b4r07/actions-opa-test@master
      with:
        path: .
        coverage: 90%
        files: ${{steps.changed.outputs.added}}
