# name: CI
# on:
#   - push
# jobs:
#   test:
#     name: 'Test'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#         with:
#           fetch-depth: 1
#       - run: npm install
#       - run: npm run build
#       - name: 'Get changed files'
#         uses: futuratrepadeira/changed-files@master
#         with:
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
#         id: changed_files
#       - name: 'Echo'
#         run: |
#           echo ${{ steps.changed_files.outputs.files_created }}
#           echo ${{ steps.changed_files.outputs.files_updated }}

name: test
on: [push]

jobs:
  opa_test:
    runs-on: ubuntu-latest
    name: Run opa
    steps:
    - name: Run with opa test
      id: hello
      uses: b4b4r07/actions-opa-test@v0.1.2
      with:
        src: 'example.rego'
        src_test: 'example_test.rego'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
