name: Run opa test

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Run opa test
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run with opa test
      uses: b4b4r07/actions-opa-test@master
      with:
        path: .
        coverage: 90%
        # files: example.rego
