name: Run opa test

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Run opa test
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Get changed objects
      uses: b4b4r07/action-changed-objects@master
      with:
        added: 'true'
        deleted: 'false'
        modified: 'true'
      id: objects
    - name: Run opa test
      uses: b4b4r07/action-opa@master
      if: steps.objects.outputs.objects
      with:
        path: .
        coverage: 90%
        files: ${{ steps.objects.outputs.objects }}
