# change this to the event type you want to get the data for
on:
  pull_request:
    # types: [opened, closed, reopened]

jobs:
  file:
    name: List files
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        # echo "$GITHUB_CONTEXT"
        # echo ${{ github.event.pull_request }}
        # echo ${{ toJson(github) }}
        url="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
        curl -s -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" ${url} | jq '.[] | select(.filename == "a.sh") | select(.status == "added")'
