# change this to the event type you want to get the data for
on:
  pull_request:
    branches:
      - master
    types: [opened, closed, reopened]

jobs:
  job1:
    name: record
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Record pull request information
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        GITHUB_REPO: ${{ github.repository }}
        PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        EVENT_ACTION: ${{ github.event.action }}
        GIST_ID: "4e0a7b5136bee6c0f86959c3723999e6"
        PULL_REQUEST_MERGED: ${{ github.event.pull_request.merged }}
      run: |
        bash scripts/api.sh
